### ISSUE TITLE
Ipeplots crashes with Ipe 7.1.7

### ISSUE THREAD

**Issue by lahvak** [lahvak/ipeplots#1]
User reported a Lua error with Ipe 7.1.7.  This is the error message as reported by the user:
```
   Lua error
   
   
   Data may have been corrupted.
   
   Save your file!
   
   
   /Users/Dillon/.ipe/ipelets/plots.lua:583: segment 1 of element 1 has
invalid type
   
   stack traceback:
   
   [C]: in function 'Path'
   
   /Users/Dillon/.ipe/ipelets/plots.lua:583: in function 'run'
   
   ../../local/share/ipe/7.1.7/lua/actions.lua:579: in function 'action_ipelet'
   
   ../../local/share/ipe/7.1.7/lua/actions.lua:83: in function 'paction'
   
   ../../local/share/ipe/7.1.7/lua/actions.lua:37: in function
   <../../local/share/ipe/7.1.7/lua/actions.lua:37>
   
   [C]: in function 'xpcall'
   
   ../../local/share/ipe/7.1.7/lua/actions.lua:37: in function
   <../../local/share/ipe/7.1.7/lua/actions.lua:36>
   
   [C]: in function 'mainloop'
   
   ../../local/share/ipe/7.1.7/lua/main.lua:444: in main chunk
   
   [C]: in function 'require'
   
    [string "require "main""]:1: in main chunk
```

**Comment by lahvak** [comment]
Currently do not have access to 7.1.7, so cannot reproduce.  Possibly related to [this issue](https://github.com/otfried/ipe/issues/5)?

**Comment by otfried** [comment]
The segment type "bezier" no longer exists in Ipe 7.1.7.  You need to use "spline" instead.

See https://github.com/otfried/ipe/issues/3.

This should have nothing to do with https://github.com/otfried/ipe/issues/5.

**Comment by lahvak** [comment]
Hopefully fixed, cannot test myself.

**Comment by lahvak** [comment]
Reported fixed.

**Comment by otfried** [comment]
If you wanted the code to work on old and new versions of Ipe, you could do

```
local beziername = "spline"
if _G.config.version < "7.1.7" then
  beziername = "bezier"
end
```

and then later use *beziername* instead of "spline".

Also, why are you putting the function ipeplot_tick_range into the global namespace?
