### ISSUE TITLE
Lua Error on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by unruhschuh** [lahvak/ipeplots#2]
Hi,

I get the following error every time I try to plot a function, parametric function or even draw a coordinate system or grid.

![ipeluaerror](https://cloud.githubusercontent.com/assets/13489581/11360465/1aef6eb0-9285-11e5-9b57-5c4a111e9d80.png)

I'm using Ipe version 7.1.10 and the latest version of ipeplots.

This works fine under Fedora 22 with Ipe version 7.1.7.

I do program, though I don't know Lua, but with some instructions I guess I could help to fix this.

Tom

**Comment by lahvak** [comment]
Can you try to replace `loadstring` with `load`?  I do not habe the newest version of Ipe nor Lua installed, so I cannot test it, but it seems that in Lua 5.2, `loadstring` was deprecated and replaced with `load`.

**Comment by unruhschuh** [comment]
Works perfectly, thanks!

**Comment by otfried** [comment]
Here is a revised version that fixes this problem and also works on Ipe 7.1.6 and earlier. (There's no reason to use "loadstring" - it was already deprecated in Lua 5.2.)

https://www.dropbox.com/s/jddxkjkja3drdjw/plots.lua?dl=0

**Comment by liubenyuan** [comment]
@otfried 

Hi, is the file you post on the dropbox merged with ipeplots ?

**Comment by otfried** [comment]
I think you need to ask this question to @lahvak.

**Comment by otfried** [comment]
Apparently not, since the file was last changed in 2015.

**Comment by liubenyuan** [comment]
@otfried can I create a pull request using your modifications ?

**Comment by otfried** [comment]
Sure.

**Comment by lahvak** [comment]
Thanks for the fix!
