### ISSUE TITLE
Dialogs do not show correctly on OSX

### ISSUE THREAD

**Issue by otfried** [lahvak/ipeplots#4]
The dialogs do not show correctly in the new Cocoa interface for Ipe.   The reason is that no button bar is created in these dialogs (instead buttons are made "by hand").

This is what it looks like now:
![shot1](https://cloud.githubusercontent.com/assets/9983417/16302074/62d61be6-3949-11e6-92f9-676643906ce4.png)

Here is a patch that fixes the problem.

[plots.patch.txt](https://github.com/lahvak/ipeplots/files/329873/plots.patch.txt)

**Comment by lahvak** [comment]
@otfried  I applied your patch, thank you!  Could you please test it works, I have no access to an OSX.

**Comment by otfried** [comment]
It works fine now.
