### ISSUE TITLE
Can't draw math.abs(50*cos((1/22.5 * pi) * x)) correctly

### ISSUE THREAD

**Issue by TornaxO7** [lahvak/ipeplots#6]
I'm trying to draw the cosinus wave were all all values are in the plus range like this in geogebra:
![image](https://user-images.githubusercontent.com/50843046/116072494-747fd180-a68f-11eb-9921-69acc6cbc7b6.png)

I tried that in Ipe with the following settings:
![image](https://user-images.githubusercontent.com/50843046/116072535-7f3a6680-a68f-11eb-8c1a-b7bf7d5fb61e.png)

But I'm getting this graph instead where the low points are differently high:
![image](https://user-images.githubusercontent.com/50843046/116072609-9aa57180-a68f-11eb-9c06-6efc05a19b9e.png)

Is that normal or can I fix that somehow?

**Comment by lahvak** [comment]
Did you try to increase the "number of points"?

**Comment by lahvak** [comment]
Also, cubic splines may not be what you want in this case, they are differentiable and your function is not.

You may want to plot only one of the "waves" and then use other Ipe features to create copies and shift them to the right.

**Comment by TornaxO7** [comment]
> Did you try to increase the "number of points"?

Doing this solved my problem, thank you!

**Comment by TornaxO7** [comment]
And thank you for this extension! :)
